name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Installed packages:"
          pip list
          
      - name: List project files
        run: |
          echo "Project structure:"
          ls -la
          echo "\nTemplates directory:"
          ls -la templates/
          echo "\nStatic directory:"
          ls -la static/
          echo "\nMedia directory:"
          ls -la Media/
          
      - name: Build static site
        run: |
          python build_static.py
          echo "\nContents of static_site directory:"
          ls -la static_site/
          echo "\nContents of static_site/static:"
          ls -la static_site/static/
          echo "\nContents of static_site/Media:"
          ls -la static_site/Media/
          
      - name: Check for build artifacts
        run: |
          if [ ! -d "static_site" ]; then
            echo "Error: static_site directory not created"
            exit 1
          fi
          if [ ! -f "static_site/index.html" ]; then
            echo "Error: index.html not found in static_site"
            exit 1
          fi
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './static_site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 